import SelectLanguages from "@/app/components/SelectLanguages";
import { DotBackgroundDemo } from "@/app/components/UI/BackgroundDot";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
	title: "About Us | La Movie",
	description: "Generated by create next app by paul la",
};

export default function AboutPage({ params }: { params: { lang: string } }) {
	return (
		<div className="about about-page">
			<div className="h-[40rem] w-full dark:bg-black bg-white  dark:bg-dot-white/[0.2] bg-dot-black/[0.2] relative flex items-center justify-center">
				{/* Radial gradient for the container to give a faded look */}
				<div className="absolute pointer-events-none inset-0 flex items-center justify-center dark:bg-black bg-white [mask-image:radial-gradient(ellipse_at_center,transparent_20%,black)]"></div>
				<div className="container m-auto max-w-5xl flex flex-col gap-10 text-center">
					<h1 className="page-title">About La Movie </h1>

					<h2 className="text-2xl">My name: La Quoc Thinh</h2>
					<p className="flex m-auto gap-1 flex-wrap items-center justify-center">
						La Movies App use
						<Link href="https://nextjs.org/" target="_blank" rel="noopener">
							Nextjs 14
						</Link>
						,
						<Link href="https://tailwindcss.com/" target="_blank" rel="noopener">
							TailWind Css
						</Link>
						and
						<Link href={"https://www.themoviedb.org/"} target="_blank" rel="noopener">
							TheMovieBD API
						</Link>
					</p>
				</div>
			</div>
		</div>
	);
}
