import { Metadata } from "next";
import Head from "next/head";
import Link from "next/link";
import React from "react";

export const metadata: Metadata = {
  title: "About Us | La Movie",
  description: "Generated by create next app by paul la",
};

export default function AboutPage() {
  return (
    <div className="about about-page">
      <div className="container max-w-5xl p-10 text-center">
        <h1 className="page-title">About Us</h1>
        <h5>My name: La Quoc Thinh</h5>
        <p className="flex m-auto gap-1 items-center justify-center">
          La Movies use
          <Link href="https://nextjs.org/">Nextjs 13</Link>
          and TheMovie BD API
          <Link href={"https://www.themoviedb.org/"}></Link>
        </p>
      </div>
    </div>
  );
}
