import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "About Us | La Movie",
  description: "Generated by create next app by paul la",
};

export default function AboutPage() {
  return (
    <div className="about about-page">
      <div className="container m-auto max-w-5xl p-10 text-center">
        <h1 className="page-title">About Us</h1>

        <h5>My name: La Quoc Thinh</h5>
        <p className="flex m-auto gap-1 flex-wrap items-center justify-center">
          La Movies App use
          <Link href="https://nextjs.org/" target="_blank" rel="noopener">
            Nextjs 13
          </Link>
          ,
          <Link href="https://tailwindcss.com/" target="_blank" rel="noopener">
            TailWind Css
          </Link>
          and
          <Link
            href={"https://www.themoviedb.org/"}
            target="_blank"
            rel="noopener"
          >
            TheMovieBD API
          </Link>
        </p>
      </div>
    </div>
  );
}
