import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";
import { Providers } from "./providers";
import { Suspense } from "react";
import Loading from "@/app/components/Loading";
import PageLoading from "./components/LoadingProgressBar";
import { Analytics } from "@vercel/analytics/react";
import { GoogleAnalytics, GoogleTagManager } from "@next/third-parties/google";

const interFont = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "La Movie App",
	description: "La Movie Generated by create next app by Paul la",
};

export async function generateStaticParams() {
	return [{ lang: "en-US" }, { lang: "vi-VN" }];
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html
			lang="en"
			className="light scroll-smooth focus:scroll-auto"
			suppressHydrationWarning
		>
			<GoogleTagManager gtmId="G-C6ZWMDMFNJ" />
			<body className={`${interFont.className} `}>
				<Providers>
					<Header />
					<PageLoading />
					<main className="main flex flex-col text-center items-start">
						<Suspense fallback={<Loading text="Loading Page" />}>{children}</Suspense>
					</main>
					<Footer />
					{/* <Analytics /> */}
					<GoogleAnalytics gaId="G-C6ZWMDMFNJ" />
				</Providers>
			</body>
		</html>
	);
}
