import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App La Movie",
  description: "Generated by create next app by paul la",
};

export async function generateStaticParams() {
  return [{ lang: "en-US" }, { lang: "vi-VN" }];
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main className="main flex flex-col text-center">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
